# Site settings
title: AiWDC Content Automation Platform
description: Connect your data, transform with AI, and publish everywhere. Automated content creation platform with multiple AI models.
url: "https://aiwdc.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  resources:
    output: true
    permalink: /resources/:name/
  articles:
    output: true
    permalink: /articles/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: resources
    values:
      layout: resource
  - scope:
      path: ""
      type: articles
    values:
      layout: article
  - scope:
      path: ""
    values:
      layout: default

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - .github/workflows

# SEO and social media
author: AiWDC
twitter:
  username: AiWDC
  card: summary_large_image
  image: https://maas-log-prod.cn-wlcb.ufileos.com/anthropic/0387fa09-fd0c-482a-9a55-40631b2ee6d8/b893dce3040f24caedd7b7e521408a6e.png?UCloudPublicKey=TOKEN_e15ba47a-d098-4fbd-9afc-a0dcf0e4e621&Expires=1758552054&Signature=9L2iIjKNfNMNDCZAz87fLYrXKQo=
social:
  name: AiWDC
  links:
    - https://twitter.com/AiWDC
    - https://linkedin.com/company/aiwdc
logo: /assets/images/logo.svg
image: https://maas-log-prod.cn-wlcb.ufileos.com/anthropic/0387fa09-fd0c-482a-9a55-40631b2ee6d8/b893dce3040f24caedd7b7e521408a6e.png?UCloudPublicKey=TOKEN_e15ba47a-d098-4fbd-9afc-a0dcf0e4e621&Expires=1758552054&Signature=9L2iIjKNfNMNDCZAz87fLYrXKQo=

# Google Analytics
google_analytics: G-50PGBTRWFQ

# GitHub Pages specific
github:
  repository_url: https://github.com/yourusername/aiwdc.com

# Navigation
navigation:
  - title: Features
    url: /#features
  - title: Pricing
    url: /#pricing
  - title: Resources
    url: /resources/
  - title: Community
    url: /#community

# Resource categories
resource_categories:
  - Documentation
  - Tutorials
  - Templates
  - Blog